import 'package:nobook/src/features/assignments/assignment_barrel.dart';
import 'package:nobook/src/utils/utils_barrel.dart';

abstract class FakeAssignmentData {
  static final List<TimeTable> timeTable = [
    TimeTable(subject: 'Maths', subjectLogo: Assets.mt),
    TimeTable(subject: 'Physics', subjectLogo: Assets.mt),
    TimeTable(subject: 'Chemistry', subjectLogo: Assets.mt),
    TimeTable(subject: 'Biology', subjectLogo: Assets.mt),
    TimeTable(subject: 'English', subjectLogo: Assets.mt),
    TimeTable(subject: 'Further Mathematics', subjectLogo: Assets.mt),
    TimeTable(subject: 'Maths', subjectLogo: Assets.mt),
    TimeTable(subject: 'Physics', subjectLogo: Assets.mt),
    TimeTable(subject: 'Chemistry', subjectLogo: Assets.mt),
    TimeTable(subject: 'Biology', subjectLogo: Assets.mt),
    TimeTable(subject: 'English', subjectLogo: Assets.mt),
    TimeTable(subject: 'Further Mathematics', subjectLogo: Assets.mt),
  ];

  static final List<Assignment> assignments = [
    Assignment(
      Assets.eco,
      'Economics',
      'Demand and Supply',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.eco,
      'Economics',
      'Demand and Supply',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.eco,
      'Economics',
      'Demand and Supply',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.eco,
      'Economics',
      'Demand and Supply',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.eco,
      'Economics',
      'Demand and Supply',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.eco,
      'Economics',
      'Demand and Supply',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.eco,
      'Economics',
      'Demand and Supply',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
  ];

  static final List<Assignment> bioassignments = [
    Assignment(
      Assets.bio,
      'Biology',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.bio,
      'Biology',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.bio,
      'Biology',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.bio,
      'Biology',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.bio,
      'Biology',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.bio,
      'Biology',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.bio,
      'Biology',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
  ];

  static final List<Assignment> bkassignments = [
    Assignment(
      Assets.bk,
      'Book Keeping',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.bk,
      'Book Keeping',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.bk,
      'Book Keeping',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.bk,
      'Book Keeping',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.bk,
      'Book Keeping',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.bk,
      'Book Keeping',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.bk,
      'Book Keeping',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
  ];

  static final List<Assignment> chassignments = [
    Assignment(
      Assets.ch,
      'Chemistry',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.ch,
      'Chemistry',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.ch,
      'Chemistry',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.ch,
      'Chemistry',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.ch,
      'Chemistry',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.ch,
      'Chemistry',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.ch,
      'Chemistry',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
  ];
  static final List<Assignment> cvassignments = [
    Assignment(
      Assets.cv,
      'Civic Educatio',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.cv,
      'Civic Educatio',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.cv,
      'Civic Educatio',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.cv,
      'Civic Educatio',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.cv,
      'Civic Educatio',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.cv,
      'Civic Educatio',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.cv,
      'Civic Educatio',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
  ];
  static final List<Assignment> engassignments = [
    Assignment(
      Assets.eng,
      'English Language',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.eng,
      'English Language',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.eng,
      'English Language',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.eng,
      'English Language',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.eng,
      'English Language',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.eng,
      'English Language',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.eng,
      'English Language',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
  ];
  static final List<Assignment> fmassignments = [
    Assignment(
      Assets.fm,
      'Further Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.fm,
      'Further Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.fm,
      'Further Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.fm,
      'Further Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.fm,
      'Further Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Undone',
    ),
    Assignment(
      Assets.fm,
      'Further Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.fm,
      'Further Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
  ];
  static final List<Assignment> geoassignments = [
    Assignment(
      Assets.geo,
      'Geography',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.geo,
      'Geography',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.geo,
      'Geography',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.geo,
      'Geography',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.geo,
      'Geography',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.geo,
      'Geography',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.geo,
      'Geography',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
  ];
  static final List<Assignment> mathassignments = [
    Assignment(
      Assets.mt,
      'Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.mt,
      'Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.mt,
      'Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.mt,
      'Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.mt,
      'Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.mt,
      'Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.mt,
      'Maths',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
  ];
  static final List<Assignment> phyassignments = [
    Assignment(
      Assets.ph,
      'Physics',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.ph,
      'Physics',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.ph,
      'Physics',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.ph,
      'Physics',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.ph,
      'Physics',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.ph,
      'Physics',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
    Assignment(
      Assets.ph,
      'Physics',
      'cvll Theory',
      '18th April, 2022, 09:31am',
      'Expires 19th April, 8:00am',
      'Submitted',
    ),
  ];
}
